// <auto-generated />
using System;
using BIMA.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BIMA.Database.Migrations
{
    [DbContext(typeof(BIMADbContext))]
    [Migration("20210323211619_dataSeedAppContent")]
    partial class dataSeedAppContent
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BIMA.Database.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CountryCode")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("District")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("BIMA.Database.Entities.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Capital")
                        .HasColumnType("text");

                    b.Property<string>("Code2")
                        .HasColumnType("text");

                    b.Property<string>("Continent")
                        .HasColumnType("text");

                    b.Property<float>("GNP")
                        .HasColumnType("float");

                    b.Property<float>("GNPOld")
                        .HasColumnType("float");

                    b.Property<string>("GovernmentForm")
                        .HasColumnType("text");

                    b.Property<string>("HeadOfState")
                        .HasColumnType("text");

                    b.Property<int>("IndepYear")
                        .HasColumnType("int");

                    b.Property<float>("LifeExpectancy")
                        .HasColumnType("float");

                    b.Property<string>("LocalName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.Property<float>("SurfaceArea")
                        .HasColumnType("float");

                    b.HasKey("Code");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("BIMA.Database.Entities.Footer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsSocialMedia")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("link")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Footers");
                });

            modelBuilder.Entity("BIMA.Database.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "DE",
                            Name = "German"
                        },
                        new
                        {
                            Id = 2,
                            Code = "ENG",
                            Name = "English"
                        });
                });

            modelBuilder.Entity("BIMA.Database.Entities.Navbar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("Navbars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "Home",
                            LanguageId = 1,
                            Name = "home",
                            Order = 1
                        },
                        new
                        {
                            Id = 2,
                            Label = "Kurse",
                            LanguageId = 1,
                            Name = "courses",
                            Order = 2
                        },
                        new
                        {
                            Id = 3,
                            Label = "Preise",
                            LanguageId = 1,
                            Name = "prices",
                            Order = 3
                        },
                        new
                        {
                            Id = 4,
                            Label = "Gemeinschaft",
                            LanguageId = 1,
                            Name = "community",
                            Order = 4
                        },
                        new
                        {
                            Id = 5,
                            Label = "Team",
                            LanguageId = 1,
                            Name = "about",
                            Order = 5
                        },
                        new
                        {
                            Id = 6,
                            Label = "Kontakt",
                            LanguageId = 1,
                            Name = "contact",
                            Order = 6
                        });
                });

            modelBuilder.Entity("BIMA.Database.Entities.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("PageContent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Pages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LanguageId = 1,
                            PageContent = @"{
                                                                      ""introTitle"": ""Erfahren Sie mehr über die digitale BIM Academy"",
                                                                      ""introContent"": ""Unsere Mission ist es mit Hilfe von modernen Bildungsansätzen wie Online Education und begleitetem Coaching das komplexe Thema BIM so einfach wie möglich unseren Studenten beizubringen./Wir sind ein Team aus digitalen Enthusiasten,  Dozenten und Experten für BIM. "",
                                                                      ""getEBookBoxContentTitle"": ""Holen Sie sich ein kostenloses eBook 'What is BIM' per E-Mail mit Registrierung!"",
                                                                      ""getEbookButtonLabel"": """",
                    ""aboutBimTitle"": ""Vorteile der digitalen BIM Academy"",
                    ""firstAboutTitle"": ""Effektives, leicht zugängliches und einzigartiges Training"",
                    ""firstAboutContent"": ""Alle unsere Kurse sind rund um die Uhr zugänglich, leicht verständlich und auf dem Markt sehr gefragt.E - Books sind nach jedem Kursmodul enthalten."",
                    ""secondAboutTitle"": ""Wählen Sie zwischen verschiedenen Feldern in der Konstruktion"",
                    ""secondAboutContent"": ""Es gibt verschiedene Kurse zur digitalen BIM - Plattform, die Ihnen alle Fähigkeiten vermitteln, die auf dem Markt dringend benötigt werden."",
                    ""thirdAboutTitle"": ""The most versatile course experience"",
                    ""thirdAboutContent"": ""Engage learners with video interactions, note - taking, interactive ebooks, self - assessment, certificates, SCORM and much more"",
                    ""fourthAboutTitle"": ""Promote the social talk"",
                    ""fourthAboutContent"": ""Engage learners with video interactions, note - taking, interactive ebooks, self - assessment, certificates, SCORM and much more"",
                    ""popularCourseTitle"": ""Die beliebtesten Kurse auf dem Bahnsteig"",
                    ""firstPopularCourseTitle"": ""Revit"",
                    ""firstPopularcourseContent"": """",
                    ""secondPopularCourseTitle"": ""What is BIM ? "",
                                                                      ""secondPopularcourseContent"": """",
                    ""thirdPopularCourseTitle"": ""ArchiCAD"",
                    ""thirdPopularcourseContent"": """",
                    ""investingSectionTitle"": ""It’s time to start investing in yourself!"",
                    ""investingSectionButton"": ""Jetzt starten!"",
                    ""PricingPageTitle"": ""Pricing plans"",
                    ""priceBoxes"": [
                                                                        {
                ""boxTitle"": ""MEMBERSHIP"",
                                                                          ""price"": ""980 CHF"",
                                                                          ""courseContent"": ""Im Preis enthalten: "",
                                                                          ""courseContentListed"": ""Onlinekurse unbegrenzt schauen / Prüfung inkl.Zertifikat zu Onlinekursen / Zugang zur Community Education Plattform/ Möglichkeit an BIM Live - Events teilzunehmen / Rabatt auf Online-Coaching mit unseren Experten""
                                                                        },
                                                                        {
                ""boxTitle"": ""ENTERPRISE"",
                                                                          ""price"": ""8‘900 CHF"",
                                                                          ""courseContent"": ""Im Preis enthalten: "",
                                                                          ""courseContentListed"": ""Das komplette Membership - Paket / Firmeninterner Bereich für Dateien und Firmenlernvideos(bis 100 GB inkl.) / Floating - Lizenz - Modell, bezahlt wird nur die Anzahl die gebraucht wird/ Exklusiver Zugang zum Bereich 'BIM - Jobs' für die Talentsuche / Möglichkeit Lernvideos durch das Team DBA produzieren zu lassen""
                                                                        },
                                                                        {
                ""boxTitle"": ""BIM 5D MASTER"",
                                                                          ""price"": ""9‘800 CHF"",
                                                                          ""courseContent"": ""Im Preis enthalten: "",
                                                                          ""courseContentListed"": ""Das komplette Membership - Paket / Onlinevorlesungen / Begleitetes Coaching durch unsere Experten/ BIM 5D Live Event/ Master - Diplom BIM 5D der digital BIM academy""
                                                                        }
                                                                      ],
                                                                      ""academyMembersTitle"": ""Unsere Academy members arbeiten bei: "",
                                                                      ""aboutUsPageTitle"": ""Unsere Mission"",
                                                                      ""aboutUsStory"": ""Lorem ipsum dolor sit amet, consectetur adipiscing elit.Nunc tincidunt augue non lacus porta, quis aliquam ipsum aliquet.Pellentesque fermentum ex at aliquam pretium. Vestibulum nec elit vitae magna ultricies interdum.Aenean et interdum dolor, vitae elementum mi. Nulla facilisi. Proin pellentesque fermentum velit non rhoncus. Suspendisse in augue ipsum. Fusce tempus scelerisque consequat. Sed iaculis pretium nibh, sit amet mattis nibh blandit at. "",
                                                                      ""teamTitle"": ""Unsere team"",
                                                                      ""teamMemberCard"": """",
                                                                      ""ourValues"": ""Unsere Werte"",
                                                                      ""valueOneTitle"": ""Wir kümmern uns um die Qualität unserer Ausbildung"",
                                                                      ""valueOneContent"": ""Wir haben das wertvollste Wissen gesammelt, um es an Sie weiterzugeben. Nur Fachleute in dieser Branche haben daran gearbeitet, das wichtigste Wissen von BIM zu kombinieren."",
                                                                      ""valueTwoTitle"": ""Wir wollen Ihre Probleme lösen!"",
                                                                      ""valueTwoContent"": ""Die Kurse richten sich speziell an die am meisten benötigten Baufelder auf dem Markt. Dies ist die perfekte Lernplattform, um alle Probleme beim Bauen zu lösen.Die Lehrer sind offen für Fragen."",
                                                                      ""valueThreeTitle"": ""Wir möchten Sie mit Menschen mit ähnlichen Interessen verbinden"",
                                                                      ""valueOneContent"": ""Wenn Sie ein Netzwerk von Menschen mit ähnlichen Interessen und in derselben Branche wie Sie haben möchten, können Sie auf unserer Community-Seite und in unseren Seminaren wertvolle Kontakte und Kunden knüpfen."",
                                                                      ""loginTitle"": ""Anmeldung"",
                                                                      ""rememberMe"": ""Behalte mihc in Erinnerung"",
                                                                      ""resetPassword"": ""Setze mein Passwort zurück"",
                                                                      ""freeRegistration"": ""Noch kein Mitglied? Kostenlos registrieren"",
                                                                      ""registrationTitle"": ""Registrieren Sie sich und starten Sie Ihre digitale BIM - Reise"",
                                                                      """": """",
                                                                      ""occupation"": ""Besetzung: "",
                                                                      ""birthDate"": ""Geburtsdatum: "",
                                                                      ""gender"": ""Geschlecht: "",
                                                                      ""country"": ""Land"",
                                                                      ""password"": ""Passwort: "",
                                                                      ""confirmPassword"": ""Kennwort bestätigen:"",
                                                                      ""registratonButton"": ""Registrieren"",
                                                                      ""userHasAccountMsg"": ""Sie haben bereits ein Konto? Hier anmelden."",
                                                                      ""coursePageTitle"": ""Kurse""
                                                                    }"
                        });
                });

            modelBuilder.Entity("BIMA.Database.Entities.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<string>("BalanceTransactionId")
                        .HasColumnType("text");

                    b.Property<string>("ChargeId")
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime");

                    b.Property<int>("PlanPrice")
                        .HasColumnType("int");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("BIMA.Database.Entities.PlanPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PlanPrices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Currency = "chf",
                            Label = "MEMBERSHIP",
                            Name = "membership",
                            Price = 98000
                        },
                        new
                        {
                            Id = 2,
                            Currency = "chf",
                            Label = "ENTERPRISE",
                            Name = "enterprise",
                            Price = 890000
                        },
                        new
                        {
                            Id = 3,
                            Currency = "chf",
                            Label = "BIM 5D MASTER",
                            Name = "bimMaster",
                            Price = 980000
                        });
                });

            modelBuilder.Entity("BIMA.Database.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ConcurrencyStamp = "df811e72-95fa-4d06-9c3d-0fa7016b1dde",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2L,
                            ConcurrencyStamp = "7d575d43-f590-475a-8785-5b88e1776944",
                            Name = "teacher",
                            NormalizedName = "TEACHER"
                        },
                        new
                        {
                            Id = 3L,
                            ConcurrencyStamp = "6236fa2c-c5cd-46ed-905f-ced532e5d0de",
                            Name = "company",
                            NormalizedName = "COMPANY"
                        },
                        new
                        {
                            Id = 4L,
                            ConcurrencyStamp = "72d2f4e3-08e7-4d26-9c62-0f52b0a8fa63",
                            Name = "member",
                            NormalizedName = "MEMBER"
                        });
                });

            modelBuilder.Entity("BIMA.Database.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<string>("CompanyUniqueStamp")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("CountryCode")
                        .HasColumnType("varchar(767)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Employment")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("Paid")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryCode");

                    b.HasIndex("LanguageId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AccessFailedCount = 0,
                            Age = 0,
                            CityId = 201,
                            ConcurrencyStamp = "d01ff263-43da-4d66-bb87-07a71d8cb145",
                            CountryCode = "BIH",
                            CreatedDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "amir@digitalbim.academy",
                            EmailConfirmed = true,
                            Employment = "Founder",
                            FirstName = "Amir",
                            Gender = 0,
                            LanguageId = 1,
                            LastName = "Sivic",
                            LockoutEnabled = false,
                            NormalizedEmail = "AMIR@DIGITALBIM.ACADEMY",
                            NormalizedUserName = "AMIRBIM",
                            Paid = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEGN6v4MkGaM0HGLN3YVuWHtr/ZyGTscvWtLDLY3o4kHjmcq7RUg5b4hiZ/malTcBfw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "47a9e07e-d491-44d4-adb5-8f67f57b7dec",
                            TwoFactorEnabled = false,
                            UserName = "amirBim"
                        },
                        new
                        {
                            Id = 2L,
                            AccessFailedCount = 0,
                            Age = 0,
                            CityId = 201,
                            ConcurrencyStamp = "5a78cd9d-b6be-4667-b7ef-ca7952338a8a",
                            CountryCode = "BIH",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2019),
                            Email = "cekic.edin@hotmail.com",
                            EmailConfirmed = true,
                            Employment = "Developer",
                            FirstName = "Edin",
                            Gender = 0,
                            LanguageId = 1,
                            LastName = "Cekic",
                            LockoutEnabled = false,
                            NormalizedEmail = "CEKIC.EDIN@HOTMAIL.COM",
                            NormalizedUserName = "EDINBIM",
                            Paid = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEGN6v4MkGaM0HGLN3YVuWHtr/ZyGTscvWtLDLY3o4kHjmcq7RUg5b4hiZ/malTcBfw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8aeae5f0-3d3a-4bdc-ae7b-ab938f2ce449",
                            TwoFactorEnabled = false,
                            UserName = "edinBim"
                        },
                        new
                        {
                            Id = 3L,
                            AccessFailedCount = 0,
                            Age = 0,
                            CityId = 201,
                            ConcurrencyStamp = "1b904309-2663-4c41-ab7e-3f4b86455bca",
                            CountryCode = "BIH",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2019),
                            Email = "anessljivo@gmail.com",
                            EmailConfirmed = true,
                            Employment = "Developer",
                            FirstName = "Anes",
                            Gender = 0,
                            LanguageId = 1,
                            LastName = "Sjivo",
                            LockoutEnabled = false,
                            NormalizedEmail = "ANESSLJIVO@GMAIL.COM",
                            NormalizedUserName = "ANESBIM",
                            Paid = false,
                            PasswordHash = "AQAAAAEAACcQAAAAEGN6v4MkGaM0HGLN3YVuWHtr/ZyGTscvWtLDLY3o4kHjmcq7RUg5b4hiZ/malTcBfw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8cb5a859-cf06-46eb-b47c-0ca13532fed8",
                            TwoFactorEnabled = false,
                            UserName = "AnesBim"
                        });
                });

            modelBuilder.Entity("BIMA.Database.Entities.UserQuestionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("QuestionType")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserQuestionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            QuestionType = 0,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2,
                            QuestionType = 1,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 3,
                            QuestionType = 2,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 4,
                            QuestionType = 3,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 5,
                            QuestionType = 0,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 6,
                            QuestionType = 1,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 7,
                            QuestionType = 2,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 8,
                            QuestionType = 3,
                            UserId = 2L
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUserRole<long>");

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            RoleId = 1L
                        },
                        new
                        {
                            UserId = 1L,
                            RoleId = 2L
                        },
                        new
                        {
                            UserId = 2L,
                            RoleId = 1L
                        },
                        new
                        {
                            UserId = 2L,
                            RoleId = 2L
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(767)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("BIMA.Database.Entities.UserRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUserRole<long>");

                    b.HasIndex("RoleId");

                    b.HasDiscriminator().HasValue("UserRole");
                });

            modelBuilder.Entity("BIMA.Database.Entities.City", b =>
                {
                    b.HasOne("BIMA.Database.Entities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryCode");
                });

            modelBuilder.Entity("BIMA.Database.Entities.Navbar", b =>
                {
                    b.HasOne("BIMA.Database.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BIMA.Database.Entities.Payment", b =>
                {
                    b.HasOne("BIMA.Database.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BIMA.Database.Entities.User", b =>
                {
                    b.HasOne("BIMA.Database.Entities.City", "City")
                        .WithMany("Users")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BIMA.Database.Entities.Country", "Country")
                        .WithMany("Users")
                        .HasForeignKey("CountryCode");

                    b.HasOne("BIMA.Database.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BIMA.Database.Entities.UserQuestionType", b =>
                {
                    b.HasOne("BIMA.Database.Entities.User", "User")
                        .WithMany("UserQuestionTypes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("BIMA.Database.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("BIMA.Database.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("BIMA.Database.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("BIMA.Database.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BIMA.Database.Entities.UserRole", b =>
                {
                    b.HasOne("BIMA.Database.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BIMA.Database.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
